storage:
  movies: /movies
  tv: /series
  animes: /animes
  downloads: /downloads

transmission:
  host: "{{ env('TRANSMISSION_HOST') }}"
  port: 9091
  username: "{{ env('TRANSMISSION_USER') }}"
  password: "{{ env('TRANSMISSION_PASS') }}"

my_anime_list:
  username: "{{ env('MY_ANIME_LIST_USERNAME') }}"

opensubtitles:
  username: "{{ env('OPENSUBTITLES_USERNAME') }}"
  password: "{{ env('OPENSUBTITLES_PASSWORD') }}"

addic7ed:
  username: "{{ env('ADDIC7ED_USERNAME') }}"
  passowrd: "{{ env('ADDIC7ED_PASSWORD') }}"
