template:
  - movie_base
  - reject_series
  - reject_audio_codecs
  - transmission_client

upgrade:
  tracking: yes
  target: 1080p bluray
  timeframe: 3 days
  propers: yes

discover:
  what:
    - movie_list: manual_movies
  from:
    - piratebay:
        category: movies
        sort_by: seeds
    - yts: yes
    - solidtorrents:
        category: Video
        sort_by: leechers
        remove_potentially_unsafe: yes
        url: https://solidtorrents.net
    - limetorrents:
        category: movies
  interval: 2 hours
  release_estimations: ignore

quality:
  - 1080p bluray
  - 1080p webdl
  - 1080p webrip
  - 1080p
  - 2160p bluray
  - 2160p webdl
  - 2160p
  - 720p bluray
  - 720p
  - dvdrip

list_match:
  from:
    - movie_list: manual_movies

exists_movie:
  - "/movies"

limit_new: 1

transmission:
  path: "/downloads/movies/complete"
  ratio: 2.0
